# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sdf < Formula
  desc "Stacked Diffs Flow — manage chains of dependent PRs"
  homepage "https://github.com/pavelpascari/sdf"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pavelpascari/sdf/releases/download/v0.3.1/sdf-darwin-amd64.tar.gz"
      sha256 "d06713f76fe9d3a6a73c8947d4fe857f170d9891e2f1d4afd15e05bf33de7b73"

      define_method(:install) do
        bin.install "sdf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pavelpascari/sdf/releases/download/v0.3.1/sdf-darwin-arm64.tar.gz"
      sha256 "5f2f15f9f7b59bcdd188985e933abeac7384c5faf21cc20536e00c5e5af2f94b"

      define_method(:install) do
        bin.install "sdf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavelpascari/sdf/releases/download/v0.3.1/sdf-linux-amd64.tar.gz"
      sha256 "6044d92bd20118c0b1ff080a786aef520d617aa76562ac48b4e1e2194413af59"
      define_method(:install) do
        bin.install "sdf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavelpascari/sdf/releases/download/v0.3.1/sdf-linux-arm64.tar.gz"
      sha256 "9dbe3465be58d7adbf613616658bab32839d409c9926478f1872386f9127c2d1"
      define_method(:install) do
        bin.install "sdf"
      end
    end
  end

  test do
    system "#{bin}/sdf", "version"
  end
end
