# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sdf < Formula
  desc "Stacked Diffs Flow — manage chains of dependent PRs"
  homepage "https://github.com/pavelpascari/sdf"
  version "0.2.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pavelpascari/sdf/releases/download/v0.2.10/sdf-darwin-amd64.tar.gz"
      sha256 "9c5bd419c5296d7cf32182e48104e54d3d462da25724851872c79125c7abb712"

      define_method(:install) do
        bin.install "sdf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pavelpascari/sdf/releases/download/v0.2.10/sdf-darwin-arm64.tar.gz"
      sha256 "e39f9d3130e74a967565008838c119f66bf706bb29200729a14e1b19c121cb39"

      define_method(:install) do
        bin.install "sdf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavelpascari/sdf/releases/download/v0.2.10/sdf-linux-amd64.tar.gz"
      sha256 "d168c5d52d70e5126ad709580434a9198214ecb691127fd0edf5bbf0ab7e832c"
      define_method(:install) do
        bin.install "sdf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavelpascari/sdf/releases/download/v0.2.10/sdf-linux-arm64.tar.gz"
      sha256 "d2a2e09b9200949483596df6a81e05634dc5ff2fe67fe0f4d89d5623ba94655e"
      define_method(:install) do
        bin.install "sdf"
      end
    end
  end

  test do
    system "#{bin}/sdf", "version"
  end
end
