# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sdf < Formula
  desc "Stacked Diffs Flow — manage chains of dependent PRs"
  homepage "https://github.com/pavelpascari/sdf"
  version "0.3.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pavelpascari/sdf/releases/download/v0.3.5/sdf-darwin-amd64.tar.gz"
      sha256 "217789b9357be01c3109d87cf59f469dc4ffe0521fb8d22edc0ad02a2fa5ad4e"

      define_method(:install) do
        bin.install "sdf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pavelpascari/sdf/releases/download/v0.3.5/sdf-darwin-arm64.tar.gz"
      sha256 "c996cfbe4123eaa54076ddccd39dc756ed0fb6efa0b474a603b89d6369806d9b"

      define_method(:install) do
        bin.install "sdf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavelpascari/sdf/releases/download/v0.3.5/sdf-linux-amd64.tar.gz"
      sha256 "a3f929c4bba71e51b8392179d927501cf6b3bb592a9b03d58bb012b89a1047b3"
      define_method(:install) do
        bin.install "sdf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pavelpascari/sdf/releases/download/v0.3.5/sdf-linux-arm64.tar.gz"
      sha256 "c5ad4f677e159bec1a037d629caa567a602fb03c86c29d4caa528caa533be885"
      define_method(:install) do
        bin.install "sdf"
      end
    end
  end

  test do
    system "#{bin}/sdf", "version"
  end
end
